version: "3.6"

services:
  library:
    container_name: ${PROJECT_NAME}_library
    image: openizr/node:2.0.1-dev
    env_file:
      - .env
    command: sh -c "dsync src/scripts/types.d.ts dist/types.d.ts & yarn && yarn run dev"
    volumes:
      - ./library:/var/www/html
      - ./:/mount
    restart: unless-stopped
  playground:
    container_name: ${PROJECT_NAME}_playground
    image: openizr/node:2.0.1-dev
    env_file:
      - .env
    ports:
      - "${HOST_IP}:${PLAYGROUND_PORT}:${PLAYGROUND_PORT}"
    command: sh -c "dsync /library/dist/ node_modules/diox/"
    volumes:
      - ./playground:/var/www/html
      - ./library:/library
    restart: unless-stopped

# For people that use a VPN
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.72.57.0/24