name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
